// <auto-generated />
using System;
using BlindMatchPAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlindMatchPAS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416124158_AddProjectsAndResearchAreas")]
    partial class AddProjectsAndResearchAreas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlindMatchPAS.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MatchedSupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MatchedSupervisorId");

                    b.HasIndex("ResearchAreaId");

                    b.HasIndex("StudentId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BlindMatchPAS.Models.ResearchArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ResearchAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("BlindMatchPAS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlindMatchPAS.Models.Project", b =>
                {
                    b.HasOne("BlindMatchPAS.Models.User", "MatchedSupervisor")
                        .WithMany()
                        .HasForeignKey("MatchedSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlindMatchPAS.Models.ResearchArea", "ResearchArea")
                        .WithMany()
                        .HasForeignKey("ResearchAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlindMatchPAS.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchedSupervisor");

                    b.Navigation("ResearchArea");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
